apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-persistentvolume
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-class
  nfs:
    path: /home/csjablonkay/tmp/kubernetes/nfsproba
    server: 192.168.99.1