apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: hello
data:
  REDIS_HOST_MASTER: redisclient-master.default.svc.cluster.local
  REDIS_HOST_SLAVE: redisclient-slave.default.svc.cluster.local