apiVersion: fission.io/v1
kind: TimeTrigger
metadata:
  creationTimestamp: null
  name: incrementer
  namespace: default
spec:
  cron: '@every 1m'
  functionref:
    functionweights: null
    name: incrementer
    type: name
